### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by obrassard-test** [obrassard/R.E.V.E#4]
TEST //
Avant de soummettre un rapport d'erreur, assurez vous d'avoir bien lu les instruction (README)

Veuillez svp, donner un titre descriptif au rapport

Pour suggérer une amélioration ou une correction veuillez remplir ce formulaire :
Pour "cocher une case" veuillez remplacer l'espace par un X entre les corchet [ ] (ex: [x])

Avec quel élément avez vous eu un problème ?:
[x] Le jeu
[ ] L'image disque [DMG] (ou le démmarage du jeu)
[ ] L'utilisation en ligne
[ ] Autre > Dans ce cas, veuillez préciser ci-dessous;

Que concerne le problème que vous avez constaté ?:
[x] Faute d'ortographe
[ ] Arret du jeu de façon innopinée
[ ] Problème d'affichage / aspect
[ ] Demande d'amélioration
[ ] Autre > Dans ce cas, veuillez préciser ci-dessous;

À quelle fréquence ce problème ce produit-il ?:
[x] À chaques fois
[ ] Parfois
[ ] Cela ne s'est produit qu'une seule fois
[ ] Je ne sais pas / je n'ai essayé qu'une fois

VEUILLEZ DÉCRIRE LE PROBLÈME ET LES ÉTAPES PERMETTANT DE LE REPRODUIRE :
il ya une faute a un endroit X

Aviez vous remarqué ce problème avec une version précédente du logiciel ?:
[ ] Oui
[ ] Non
[x] Je ne sais pas

Autre commentaires (facultatif)

MERCI DE VOTRE CONTRIBUTION !

**Comment by obrassard** [comment]
> 

> @ @
